services:
  db:
    image: postgres:17
    container_name: tg-miniapp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tgminiapp
    ports:
      - "5432:5432"
    volumes:
      - tgminiapp_pg:/var/lib/postgresql/data

volumes:
  tgminiapp_pg:
